name: "Workflow yml"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  workflow-auto:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_SECRETS_TEST: ${{ secrets.REPOSITORY_SECRETS_TEST }}
    steps: 
      - uses: actions/checkout@v2
      - run: |
        echo "ref: $REPOSITORY_SECRETS_TEST"
      - run: ./scripts/workflow_auto.sh