name: "Workflow yml"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  workflow-auto:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: ./scripts/workflow_auto.sh