name: "Workflow dispatch yml"

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false
      ifRun:
        description: 'If run flow, input "run"'
        required: true
        default: ''


jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "hash: ${{ github.sha }}" 
        echo "ref: ${{ github.ref }}" 
        echo "PR head ref: ${{ github.event.pull_request.head.ref }}" 
        echo "PR Label: ${{ github.event.pull_request.labels.*.name }}" 